#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager spotifyd

## Restore Wallpaper
nitrogen --restore

## Weather Daemon
ntfd &

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &

## Launch Polybar
bash ~/.config/openbox/polybar/launch.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
# exec mpd &
exec playerctld &

#$ Spotify Daemon
exec spotifyd &
#--no-daemon &

## Launch Plank
# exec plank &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

